name: Release

on: [push, pull_request]

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #      - name: Semantic Release
      #        uses: cycjimmy/semantic-release-action@v2
      #        with:
      #          branch: enable-semantic-releases
      #          extra_plugins: |
      #            @semantic-release/release-notes-generator
      #            @semantic-release/changelog
      #            @semantic-release/git
      #          dry_run: true
      #        env:
      #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          #registry-url: https://registry.npmjs.org/

      - run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/release-notes-generator

      - run: semantic-release
